server:
  port: 8080

spring:
  application:
    name: docuagent-local
  datasource:
    url: jdbc:sqlite:../storage/app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  storage:
    templates-dir: ../templates
    generated-dir: ../storage/generated
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
